Repository babylonhealth/Stevenson, pull requests merged in 2019-12, with the labels that each got.

#41 Update GithubService+IssueComment.swift
  Sources/App/GithubService+IssueComment.swift
Labels: 👶 Trivial, 🚀 Ready for Review

#43 [IOSP-171] Add verbose logs to help debug CRP issues + use SlowClient for JIRA
  Sources/App/CRP/JiraService+CRP.swift
  Sources/App/CRP/SlackCommand+CRP.swift
  Sources/App/configure.swift
  Sources/Stevenson/JiraService+FieldTypes.swift
  Sources/Stevenson/JiraService.swift
  Sources/Stevenson/SlowClient.swift
  Tests/AppTests/AppTests.swift
Labels: 🚀 Ready for Review

#45 [IOSP-414] CRP Bot: Reuse existing Jira version if already existing
  Sources/App/CRP/JiraService+CRP.swift
  Sources/Stevenson/Errors.swift
  Sources/Stevenson/JiraService.swift
  Tests/AppTests/AppTests.swift
Labels: 🆕 Feature, 🚀 Ready for Review
