Repository babylonhealth/Stevenson, pull requests merged in 2019-10, with the labels that each got.

#35 [IOSP-194] Add IOSP and ANDRP projects to whitelist
  Sources/App/configure.swift
Labels: 🚀 Ready for Review

#32 [CNSMR-2888] Migrate slack command from hockeyapp to appcenter
  Sources/App/Fastlane/SlackCommand+Fastlane.swift
  Sources/App/configure.swift
Labels: 🚀 Ready for Review

#34 [IOSP-121] Use one main slack command
  Sources/App/Fastlane/SlackCommand+Fastlane.swift
  Sources/App/MainCommand.swift
  Sources/App/configure.swift
  Sources/Stevenson/SlackService.swift
Labels: 🚀 Ready for Review

#36 [IOSP-233] Update links to new GitHub org name
  .github/CODEOWNERS
  README.md
  Sources/App/RepoMapping.swift
Labels: 🚀 Ready for Review

#39 [IOSP-146] Whitelist new Test Kits board
  Sources/App/configure.swift
Labels: 👶 Trivial, 🚀 Ready for Review

#38 [IOSP-254] Fix CRP Bot after board requirement changes
  .circleci/config.yml
  .gitignore
  .swift-version
  Package.resolved
  Package.swift
  Sources/App/CRP/JiraService+CRP.swift
  Sources/Stevenson/Codable Utils/AnyCodable.swift
  Sources/Stevenson/Codable Utils/CustomCodable.swift
  Sources/Stevenson/Codable Utils/YMDDateCodableTransformer.swift
  Sources/Stevenson/JiraService.swift
  Tests/AppTests/AppTests.swift
  Tests/AppTests/TestUtils.swift
  cloud.yml
  web.Dockerfile
Labels: ⚒ Infrastructure, 🚀 Ready for Review
