Repository babylonhealth/Stevenson, pull requests merged in 2020-03, with the labels that each got.

#49 [IOSP-609] Fix JIRA API failing to post accountable person field
  .gitignore
  Sources/App/CRP/JiraService+CRP.swift
  Sources/Stevenson/JiraService+FieldTypes.swift
  Tests/AppTests/AppTests.swift
  Tests/AppTests/XCTestManifests.swift
Labels: 🚀 Ready for Review

#50 [IOSP-599] Whitelist multiple new JIRA projects
  Sources/App/configure.swift
Labels: 👶 Trivial, 🚀 Ready for Review

#51 [IOSP-599] Whitelist multiple new JIRA next-gen projects
  Sources/App/configure.swift
Labels: 👶 Trivial, 🚀 Ready for Review

#52 [IOSP-623] Add SDKS as board filtered in for SDK
  Sources/App/CRP/ChangelogSection.swift
  Tests/AppTests/AppTests.swift
  Tests/AppTests/XCTestManifests.swift
Labels: 🚀 Ready for Review

#53 [IOSP-633] Add COVID bugs (next-gen) JIRA project to whitelist
  Sources/App/configure.swift
Labels: 👶 Trivial

#54 Update CODEOWNERS to fix review assignment
  .github/CODEOWNERS
Labels: 👶 Trivial, 🚀 Ready for Review

#55 [IOSP-645] Add RM & TCN JIRA projects to whitelist
  Sources/App/configure.swift
Labels: 👶 Trivial, 🚀 Ready for Review
