Repository babylonhealth/Stevenson, pull requests merged in 2020-11, with the labels that each got.

#77 [PDT-1937] Support new CRP requirements
  Sources/App/CRP/JiraService+CRP.swift
  Tests/AppTests/AppTests.swift
Labels: 🚀 Ready for Review

#76 Added badges to README
  README.md
Labels: hacktoberfest-accepted, 👶 Trivial, 📚 Documentation

#78 [CNSMR-3719] Added GAA project to allow on CRP creation
  Sources/App/configure.swift
Labels: 👶 Trivial, 🚀 Ready for Review
